DoAnChuyenNganh/DoAnChuyenNganh/Controllers/QuanLyShipperController.cs
using DoAnChuyenNganh.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnChuyenNganh.Controllers
{
    [Authorize(Roles = "QuanTri,QuanLyShipper")]
    public class QuanLyShipperController : Controller
    {
        Ship2hEntities db = new Ship2hEntities();
        // GET: QuanLyThanhVien
        public ActionResult Index(int? page)
        {
            if (Session["TaiKhoan"] != null)
            {
                int PageSize = 9;
                int PageNumber = (page ?? 1);
                return View(db.Shippers.OrderBy(n => n.MaShipper).ToPagedList(PageNumber, PageSize));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }

        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                Shipper tv = db.Shippers.SingleOrDefault(n => n.MaShipper == id);
                if (tv == null)
                {
                    return HttpNotFound();
                }

                return View(tv);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ChinhSua(Shipper sp)
        {
            Shipper tvUpdate = db.Shippers.Single(n => n.MaShipper == sp.MaShipper);
            ViewBag.MaCaLam = new SelectList(db.CaLams.OrderBy(n => n.CaLam1), "MaCa", "CaLam1", sp.MaCa);
            tvUpdate.HoTen = sp.HoTen;
            tvUpdate.Email = sp.Email;
            tvUpdate.SDT = sp.SDT;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Xoa(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                Shipper tv = db.Shippers.SingleOrDefault(n => n.MaShipper == id);
                if (tv == null)
                {
                    return HttpNotFound();
                }
                return View(tv);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpPost]
        public ActionResult Xoa(int id)
        {
            try
            {
                Shipper tv = db.Shippers.SingleOrDefault(n => n.MaShipper == id);
                db.Shippers.Remove(tv);
                ViewBag.ThongbaoxoaShipper = "Đã xóa Shipper thành công";
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.ThongbaoxoaShipper = "Shipper này đang có đơn hàng, không thể xóa";
                return View(db.Shippers.SingleOrDefault(n => n.MaShipper == id));
            }
        }
        public ActionResult ShipperChuaPhanCong(int? page)
        {
            if (Session["TaiKhoan"] != null)
            {
                int PageSize = 9;
                int PageNumber = (page ?? 1);
                return View(db.Shippers.Where(n => n.MaCa == null && n.MaKho == null).OrderBy(n => n.MaShipper).ToPagedList(PageNumber, PageSize));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        public ActionResult PhanCong(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                Shipper tv = db.Shippers.SingleOrDefault(n => n.MaShipper == id);
                var listKho = db.Khoes.OrderBy(n => n.MaKho);
                var listCaLam = db.CaLams.OrderBy(n => n.MaCa);
                ViewBag.listKho = listKho;
                ViewBag.listCaLam = listCaLam;
                ViewBag.MaKho = new SelectList(db.Khoes.OrderBy(n => n.MaKho), "MaKho", "TenKho", tv.MaKho);
                ViewBag.MaCa = new SelectList(db.CaLams.OrderBy(n => n.MaCa), "MaCa", "CaLam1", tv.MaCa);
                if (tv == null)
                {
                    return HttpNotFound();
                }
                return View(tv);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpPost]
        public ActionResult PhanCong(Shipper sp)
        {
            Shipper tvUpdate = db.Shippers.Single(n => n.MaShipper == sp.MaShipper);
            int id = (int)sp.MaKho;
            tvUpdate.MaCa = sp.MaCa;
            tvUpdate.MaKho = sp.MaKho;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyShipper/ChinhSua.cshtml
@model DoAnChuyenNganh.Models.Shipper
@{
    ViewBag.Title = "Chỉnh Sửa";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h3 class="title1">Chỉnh sửa thông tin shipper @Model.HoTen</h3>
<div class="form-three widget-shadow">
    @using (Html.BeginForm("ChinhSua", "QuanLyShipper", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("MaShipper", Model.MaShipper);
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Họ tên</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập tên họ tên" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Số điện thoại</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập số điện thoại" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập số điện thoại" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <button type="submit" class="btn btn-default">Chỉnh sửa</button>
    }
</div>
<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyShipper/Index.cshtml
@using DoAnChuyenNganh.Models
@using PagedList.Mvc
@model PagedList.IPagedList<Shipper>
@{
    ViewBag.Title = "Danh sách Shipper";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}
<ul class="tabs">
    <li role="presentation" class="tablinks active"><a href="@Url.Action("Index")">Danh sách shipper</a></li>
    <li role="presentation" class="tablinks "><a href="@Url.Action("ShipperChuaPhanCong")">Danh sách shipper chưa được phân vào kho và phân ca làm</a></li>
</ul>
<div class="form-three widget-shadow">
    <table class="table">
        <thead>
            <tr>
                <th>Mã shipper</th>
                <th>Họ tên</th>
                <th>Tên đăng nhập</th>
                <th>Số điện thoại</th>
                <th>Email</th>
                <th>Ca làm</th>
                <th>Loại thành viên</th>
                <th>Đang đi giao</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaShipper)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenDangNhap)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoTen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SDT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CaLam.CaLam1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LoaiThanhVien.TenLoaiThanhVien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DangDiGiao)
                </td>
                <td>
                    @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { id = item.MaShipper }) |
                    @Html.ActionLink("Xóa", "Xoa", new { id = item.MaShipper })
                </td>

            </tr>
            }
        </tbody>
    </table>
</div>
<div class="dlink">
    <br />
    Trang@( Model.PageCount<Model.PageNumber ? 0: Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
 <style>
        .FooterAdmin {
            display: none;
        }

        .tabs {
            display: flex;
        }

        .tablinks {
            border: none;
            outline: none;
            cursor: pointer;
            width: 100%;
            padding: 1rem;
            font-size: 13px;
            text-transform: uppercase;
            font-weight: 600;
            transition: 0.2s ease;
        }

            .tablinks:hover {
                background: aqua;
                color: #fff;
            }
            /* Tab active */
            .tablinks.active {
                background: aqua;
                color: #fff;
            }

        /* tab content */
        .tabcontent {
            display: none;
        }
            /* Text*/
            .tabcontent p {
                color: #333;
                font-size: 16px;
            }
            /* tab content active */
            .tabcontent.active {
                display: block;
            }
    </style>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyShipper/PhanCong.cshtml
@using DoAnChuyenNganh.Models
@model Shipper
@{
    ViewBag.Title = "Phân Công";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h3 class="title1">Chỉnh sửa thông tin shipper @Model.HoTen</h3>
<div class="form-three widget-shadow">
    @using (Html.BeginForm("PhanCong", "QuanLyShipper", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("MaShipper", Model.MaShipper);
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Kho</label>
            <div class="col-sm-8">
                @Html.DropDownList("MaKho", null, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Ca làm</label>
            <div class="col-sm-8">
                @Html.DropDownList("MaCa", null, new { @class = "form-control" })
            </div>
        </div>

        <button type="submit" class="btn btn-default">Chỉnh sửa</button>
    }
</div>
<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>
<div class="panel-body widget-shadow">
    @{ IEnumerable<CaLam> listCaLam = (IEnumerable<CaLam>)ViewBag.listCaLam;}
    <h4>Danh sách ca làm </h4>
    <table class="table">
        <thead>
            <tr>
                <th>Mã Ca</th>
                <th>Thời gian vào ca </th>
                <th>Thời gian kết thúc ca</th>
                <th>Ca làm</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in listCaLam)
            {
                <tr>
                    <td>
                        @item.MaCa
                    </td>
                    <td>
                        @item.ThoiGianBatDau
                    </td>

                    <td>
                        @item.ThoiGianKetThuc
                    </td>
                    <td>
                        @item.CaLam1
                    </td>

                </tr>
            }

        </tbody>
    </table>
</div>
<div class="panel-body widget-shadow">
    @{ IEnumerable<Kho> listKho = (IEnumerable<Kho>)ViewBag.listKho;}
    <h4>Danh sách kho </h4>
    <table class="table">
        <thead>
            <tr>
                <th>Mã Kho</th>
                <th>Tên Kho </th>
                <th>Khu Vực</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in listKho)
            {
                <tr>
                    <td>
                        @item.MaKho
                    </td>
                    <td>
                        @item.TenKho
                    </td>

                    <td>
                        @item.KhuVuc.TenKhuVuc
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyShipper/ShipperChuaPhanCong.cshtml
@using DoAnChuyenNganh.Models
@using PagedList.Mvc
@model PagedList.IPagedList<Shipper>
@{
    ViewBag.Title = "Danh Sách Shipper Chưa Phân Công";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}
<ul class="tabs">
    <li role="presentation" class="tablinks "><a href="@Url.Action("Index")">Danh sách shipper</a></li>
    <li role="presentation" class="tablinks active"><a href="@Url.Action("ShipperChuaPhanCong")">Danh sách shipper chưa được phân vào kho và phân ca làm</a></li>
</ul>
<div class="form-three widget-shadow">
    <table class="table">
        <thead>
            <tr>
                <th>Mã shipper</th>
                <th>Họ tên</th>
                <th>Tên đăng nhập</th>
                <th>Số điện thoại</th>
                <th>Email</th>
                <th>Ca làm</th>
                <th>Loại thành viên</th>
                <th>Kho</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaShipper)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenDangNhap)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HoTen)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SDT)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CaLam.CaLam1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LoaiThanhVien.TenLoaiThanhVien)
                    </td>          
                    <td>
                        @Html.DisplayFor(modelItem=> item.Kho.TenKho)
                    </td>
                    <td>
                        @Html.ActionLink("Phân ca làm vs phân kho", "PhanCong", new { id = item.MaShipper }) 
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>
<div class="dlink">
    <br />
    Trang@( Model.PageCount<Model.PageNumber ? 0: Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .FooterAdmin {
        display: none;
    }

    .tabs {
        display: flex;
    }

    .tablinks {
        border: none;
        outline: none;
        cursor: pointer;
        width: 100%;
        padding: 1rem;
        font-size: 13px;
        text-transform: uppercase;
        font-weight: 600;
        transition: 0.2s ease;
    }

        .tablinks:hover {
            background: aqua;
            color: #fff;
        }
        /* Tab active */
        .tablinks.active {
            background: aqua;
            color: #fff;
        }

    /* tab content */
    .tabcontent {
        display: none;
    }
        /* Text*/
        .tabcontent p {
            color: #333;
            font-size: 16px;
        }
        /* tab content active */
        .tabcontent.active {
            display: block;
        }
</style>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyShipper/Xoa.cshtml
@model DoAnChuyenNganh.Models.Shipper
@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h2>Xoa</h2>

<h3 class="title1">Xóa Shipper</h3>
<h4 class="text-danger">Bạn có chắc chắn xóa shipper này chứ?</h4>
<br />
<div class="blank-page widget-shadow scroll" id="style-2 div1">
    <h4>Thông tin shipper</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã Shipper
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaShipper)
        </dd>

        <dt>
            Tên Shipper
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            Ca Làm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaLam.CaLam1)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại danh sách", "Index")
        </div>
    }
    <h4 class="text-danger">@ViewBag.ThongbaoxoaShipper</h4>
</div>