DoAnChuyenNganh/DoAnChuyenNganh/Controllers/PhanQuyenController.cs
using DoAnChuyenNganh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnChuyenNganh.Controllers
{
    [Authorize(Roles = "QuanTri")]
    public class PhanQuyenController : Controller
    {
        Ship2hEntities db = new Ship2hEntities();
        
        // GET: PhanQuyen
        public ActionResult Index()
        {
            if (Session["TaiKhoan"] != null)
            {
                return View(db.LoaiThanhViens.Where(n=>n.MaLoaiThanhVien!=7).OrderBy(n => n.TenLoaiThanhVien));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpGet]
        public ActionResult PhanQuyen(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                LoaiThanhVien ltv = db.LoaiThanhViens.SingleOrDefault(n => n.MaLoaiThanhVien == id);
                if (ltv == null)
                {
                    return HttpNotFound();
                }
                ViewBag.MaQuyen = db.Quyens;
                ViewBag.LoaiTVQuyen = db.LoaiThanhVien_Quyen.Where(n => n.MaLTV == id);
                return View(ltv);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpPost]
        public ActionResult PhanQuyen(int? MaLTV, IEnumerable<LoaiThanhVien_Quyen> listPhanQuyen)
        {
            var listDaPhanQuyen = db.LoaiThanhVien_Quyen.Where(n => n.MaLTV == MaLTV);
            if (listDaPhanQuyen.Count() != 0)
            {
                db.LoaiThanhVien_Quyen.RemoveRange(listDaPhanQuyen);
                db.SaveChanges();
            }
            if (listPhanQuyen != null)
            {
                foreach (var item in listPhanQuyen)
                {
                    item.MaLTV = int.Parse(MaLTV.ToString());
                    db.LoaiThanhVien_Quyen.Add(item);
                }
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

DoAnChuyenNganh/DoAnChuyenNganh/Views/PhanQuyen/Index.cshtml
@using DoAnChuyenNganh.Models;
@model IEnumerable<LoaiThanhVien>
@{
    ViewBag.Title = "Danh sách quyền";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}

@grid.GetHtml(
         tableStyle: "divTable",
         headerStyle: "gridHead",
         footerStyle: "gridFooter",
         rowStyle: "gridRow",
         alternatingRowStyle: "gridAltRow",
         columns: grid.Columns(
            grid.Column("MaLoaiThanhVien", "Mã loại thành viên"),
            grid.Column("TenLoaiThanhVien", "Tên loại thành viên"),
            grid.Column(format: p => Html.ActionLink("Phân Quyền", "PhanQuyen", new { id = p.MaLoaiThanhVien }))

            ))
<style>
    .divTable {
        border: 1px solid #999999;
        width: 100%;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: firebrick;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    /*.gridRow{
        color: #fff;
        background-color: blueviolet;
    }
    .gridAltRow{
        color: #fff;
        background-color: darkorange;
    }*/
</style>
<style>
    .FooterAdmin {
        display: none;
    }
</style>

DoAnChuyenNganh/DoAnChuyenNganh/Views/PhanQuyen/PhanQuyen.cshtml
@using DoAnChuyenNganh.Models;
@model LoaiThanhVien

@{
    ViewBag.Title = "Phân Quyền";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h1>Phân quyền</h1>
<h2 style="color:red;">Loại thành viên: <font color="orange"> @Model.TenLoaiThanhVien</font></h2>
<br />
@{
    //Lay danh sach quyen
    IEnumerable<Quyen> listQuyen = (IEnumerable<Quyen>)ViewBag.MaQuyen;
    IEnumerable<LoaiThanhVien_Quyen> listLTVQuyen = (IEnumerable<LoaiThanhVien_Quyen>)ViewBag.LoaiTVQuyen;
}
@using (Html.BeginForm())
{
    @Html.Hidden("MaLTV", Model.MaLoaiThanhVien)
    if (listLTVQuyen != null)
    {
        for (int j = 0; j < listQuyen.Count(); j++)
        {
            int k = 0;
            for (int i = 0; i < listLTVQuyen.Count(); i++)
            {
                if (listQuyen.ElementAt(j).MaQuyen == listLTVQuyen.ElementAt(i).MaQuyen)
                {
                    k++;
                    break;
                }
            }
            if (k != 0)
            {
                <div class="col-md-4" style="font-size: 15pt;">

                    <input class="ckb_click" checked="checked" style="width:20px;height:20px;" type="checkbox" name="@Url.Content("["+j+"].MaQuyen")" value="@listQuyen.ElementAt(j).MaQuyen" /> @listQuyen.ElementAt(j).TenQuyen
                </div>
            }
            else
            {
                <div class="col-md-4" style="font-size:15pt;">
                    <input class="ckb_click" style="width:20px;height:20px;" type="checkbox" name="@Url.Content("["+j+"].MaQuyen")" value="@listQuyen.ElementAt(j).MaQuyen" /> @listQuyen.ElementAt(j).TenQuyen
                </div>
            }
            k = 0;
        }
    }
    else
    {
        for (int i = 0; i < listQuyen.Count(); i++)
        {
            <div class="col-md-4" style="font-size:15pt;">
                <input class="ckb_click" style="width:20px;height:20px;" type="checkbox" name="@Url.Content("["+i+"].MaQuyen")" value="@listQuyen.ElementAt(i).MaQuyen" /> @listQuyen.ElementAt(i).TenQuyen
            </div>
        }
    }
    <div class="clearfix"></div>
    <input type="submit" value="Thực hiện" class="btn btn-success" />
}
<br />

@Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-primary" })
<script>
    $(".ckb_click").click(function () {
        i = 0;
        $(".ckb_click").each(function () {
            if ($(this).is(':checked')) {
                $(this).attr("name", "[" + i + "].MaQuyen");
                i++;
            }
        })
    })
</script>