DoAnChuyenNganh/DoAnChuyenNganh/Controllers/QuanLyThanhVienController.cs
using DoAnChuyenNganh.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DoAnChuyenNganh.Controllers
{
    [Authorize(Roles = "QuanTri")]
    public class QuanLyThanhVienController : Controller
    {
        Ship2hEntities db = new Ship2hEntities();
        // GET: QuanLyThanhVien
        public ActionResult Index(int? page)
        {
            if (Session["TaiKhoan"] != null)
            {
                int PageSize = 9;
                int PageNumber = (page ?? 1);
                return View(db.ThanhViens.OrderBy(n => n.MaThanhVien).ToPagedList(PageNumber, PageSize));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.MaThanhVien == id);
                ViewBag.MaLoaiThanhVien = new SelectList(db.LoaiThanhViens.OrderBy(n => n.MaLoaiThanhVien), "MaLoaiThanhVien", "TenLoaiThanhVien", tv.MaLoaiThanhVien);
                if (tv == null)
                {
                    return HttpNotFound();
                }
                return View(tv);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ChinhSua(ThanhVien tv)
        {

            ThanhVien tvUpdate = db.ThanhViens.Single(n => n.MaThanhVien == tv.MaThanhVien);

            tvUpdate.HoTen = tv.HoTen;
            tvUpdate.Email = tv.Email;
            tvUpdate.SDT = tv.SDT;
            tvUpdate.DiaChi = tv.DiaChi;
            tvUpdate.MaLoaiThanhVien = tv.MaLoaiThanhVien;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Xoa(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.MaThanhVien == id);
                if (tv == null)
                {
                    return HttpNotFound();
                }
                return View(tv);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpPost]
        public ActionResult Xoa(int id)
        {  
                ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.MaThanhVien == id);
                if (tv.MaLoaiThanhVien==1)
                {
                    ViewBag.ThongBaoXoa = "Bạn không có quyền xóa Admin";
                    return View(tv);
                }
                db.ThanhViens.Remove(tv);
                db.SaveChanges();
                return RedirectToAction("Index");
        }
        public ActionResult ThanhVienChuaPhanLoai(int? page)
        {
            if (Session["TaiKhoan"] != null)
            {
                int PageSize = 9;
                int PageNumber = (page ?? 1);
                return View(db.ThanhViens.Where(n => n.MaLoaiThanhVien == null).OrderBy(n => n.MaThanhVien).ToPagedList(PageNumber, PageSize));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpGet]
        public ActionResult PhanLoai(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.MaThanhVien == id&&n.MaLoaiThanhVien==null);
                ViewBag.MaLoaiThanhVien = new SelectList(db.LoaiThanhViens.OrderBy(n => n.MaLoaiThanhVien), "MaLoaiThanhVien", "TenLoaiThanhVien", tv.MaLoaiThanhVien);
                if (tv == null)
                {
                    return HttpNotFound();
                }
                return View(tv);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult PhanLoai(ThanhVien tv)
        {

            ThanhVien tvUpdate = db.ThanhViens.Single(n => n.MaThanhVien == tv.MaThanhVien);
            tvUpdate.MaLoaiThanhVien = tv.MaLoaiThanhVien;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyThanhVien/ChinhSua.cshtml
@model DoAnChuyenNganh.Models.ThanhVien

@{
    ViewBag.Title = "Chỉnh Sửa";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h3 class="title1">Chỉnh sửa thông tin thành viên @Model.HoTen</h3>
<div class="form-three widget-shadow">
    @using (Html.BeginForm("ChinhSua", "QuanLyThanhVien", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("MaThanhVien", Model.MaThanhVien);
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Họ tên</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập tên họ tên" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Số điện thoại</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập số điện thoại" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Địa chỉ</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", @placeholder = " Nhập địa chỉ" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập Email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Loại thành viên</label>
            <div class="col-sm-8">
                @Html.DropDownList("MaLoaiThanhVien", null, new { @class = "form-control" })
            </div>
        </div>
        <button type="submit" class="btn btn-default">Chỉnh sửa</button>
    }
</div>
<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyThanhVien/Index.cshtml
@using DoAnChuyenNganh.Models
@using PagedList.Mvc
@model PagedList.IPagedList<ThanhVien>


@{
    ViewBag.Title = "Danh sách thành viên";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}
<ul class="tabs">
    <li role="presentation" class="tablinks active"><a href="@Url.Action("Index")">Danh sách thành viên</a></li>
    <li role="presentation" class="tablinks "><a href="@Url.Action("ThanhVienChuaPhanLoai")">Danh sách thành viên chưa phân loại</a></li>
</ul>
<h2>Danh sách thành viên</h2>
<div class="form-three widget-shadow">
    <table class="table">
        <thead>
            <tr>
                <th>Mã Thành Viên</th>
                <th>Họ tên</th>
                <th>Tên đăng nhập</th>
                <th>Số điện thoại</th>
                <th>Email</th>
                <th>Địa chỉ</th>
                <th>Loại thành viên</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaThanhVien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenDangNhap)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoTen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SDT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LoaiThanhVien.TenLoaiThanhVien)
                </td>
                <td>
                    @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { id = item.MaThanhVien }) |
                    @Html.ActionLink("Xóa", "Xoa", new { id = item.MaThanhVien })
                </td>
                
            </tr>
            }
         </tbody>   
    </table>
</div>
<div class="dlink">
    <br/>
    Trang@( Model.PageCount<Model.PageNumber ? 0: Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .FooterAdmin {
        display: none;
    }

    .tabs {
        display: flex;
    }

    .tablinks {
        border: none;
        outline: none;
        cursor: pointer;
        width: 100%;
        padding: 1rem;
        font-size: 13px;
        text-transform: uppercase;
        font-weight: 600;
        transition: 0.2s ease;
    }

        .tablinks:hover {
            background: aqua;
            color: #fff;
        }
        /* Tab active */
        .tablinks.active {
            background: aqua;
            color: #fff;
        }

    /* tab content */
    .tabcontent {
        display: none;
    }
        /* Text*/
        .tabcontent p {
            color: #333;
            font-size: 16px;
        }
        /* tab content active */
        .tabcontent.active {
            display: block;
        }
</style>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyThanhVien/PhanLoai.cshtml
@model DoAnChuyenNganh.Models.ThanhVien
@{
    ViewBag.Title = "Phân Loại";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h3 class="title1">Phân loại cho thành viên thành viên @Model.HoTen</h3>
<div class="form-three widget-shadow">
    @using (Html.BeginForm("PhanLoai", "QuanLyThanhVien", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("MaThanhVien", Model.MaThanhVien);
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Loại thành viên</label>
            <div class="col-sm-8">
                @Html.DropDownList("MaLoaiThanhVien", null, new { @class = "form-control" })
            </div>

        </div>
        <button type="submit" class="btn btn-default">Phân loại</button>
    }
</div>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyThanhVien/ThanhVienChuaPhanLoai.cshtml
@using DoAnChuyenNganh.Models
@using PagedList.Mvc
@model PagedList.IPagedList<ThanhVien>

@{
    ViewBag.Title = "Thành viên chưa phân loại";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}
<ul class="tabs">
    <li role="presentation" class="tablinks "><a href="@Url.Action("Index")">Danh sách thành viên</a></li>
    <li role="presentation" class="tablinks active"><a href="@Url.Action("ThanhVienChuaPhanLoai")">Danh sách thành viên chưa phân loại</a></li>
</ul>
<h2>Danh sách thành viên chưa được phân loại</h2>
<div class="form-three widget-shadow">
    <table class="table">
        <thead>
            <tr>
                <th>Mã Thành Viên</th>
                <th>Họ tên</th>
                <th>Tên đăng nhập</th>
                <th>Số điện thoại</th>
                <th>Email</th>
                <th>Địa chỉ</th>
                <th>Loại thành viên</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaThanhVien)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenDangNhap)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HoTen)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SDT)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DiaChi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LoaiThanhVien.TenLoaiThanhVien)
                    </td>
                    <td>
                        @Html.ActionLink("Phân loại", "PhanLoai", new { id = item.MaThanhVien })
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>
<div class="dlink">
    <br />
    Trang@( Model.PageCount<Model.PageNumber ? 0: Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .FooterAdmin {
        display: none;
    }

    .tabs {
        display: flex;
    }

    .tablinks {
        border: none;
        outline: none;
        cursor: pointer;
        width: 100%;
        padding: 1rem;
        font-size: 13px;
        text-transform: uppercase;
        font-weight: 600;
        transition: 0.2s ease;
    }

        .tablinks:hover {
            background: aqua;
            color: #fff;
        }
        /* Tab active */
        .tablinks.active {
            background: aqua;
            color: #fff;
        }

    /* tab content */
    .tabcontent {
        display: none;
    }
        /* Text*/
        .tabcontent p {
            color: #333;
            font-size: 16px;
        }
        /* tab content active */
        .tabcontent.active {
            display: block;
        }
</style>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyThanhVien/Xoa.cshtml
@model DoAnChuyenNganh.Models.ThanhVien
@{
    ViewBag.Title = "Xoá";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h3 class="title1">Xóa thành viên</h3>
<h2 class="text-danger">@ViewBag.ThongBaoXoa</h2>
<h4 class="text-danger">Bạn có chắc chắn xóa thành viên này chứ?</h4>
<br />

<div class="blank-page widget-shadow scroll" id="style-2 div1">
    <h4> Thông tin thành viên</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã thành viên
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaThanhVien)
        </dd>
        <dt>
            Họ tên thành viên
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>
        <dt>
            Địa chỉ
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt>
            Email
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            Số điện thoại
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại danh sách", "Index")
        </div>
    }
</div>