DoAnChuyenNganh/DoAnChuyenNganh/Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnChuyenNganh.Models;
namespace DoAnChuyenNganh.Controllers
{
    [Authorize(Roles = "QuanTri,QuanLyDonHang")]
    public class QuanLyDonHangController : Controller
    {
        // GET: QuanLyDonHang
        Ship2hEntities db = new Ship2hEntities();
        public ActionResult DonHangChuaCoShipper()
        {
            if (Session["TaiKhoan"] != null)
            {
                var listDSDHCG = db.DonDatHangs.Where(n => n.MaShipper == null && n.DaThanhToan == false && n.TinhTrangGiaoHang ==false).OrderBy(n => n.ThoiGianDat);
                return View(listDSDHCG);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        public ActionResult ChuaThanhToanChuaGiao()
        {
            if (Session["TaiKhoan"] != null)
            {
                var listDSDHCG = db.DonDatHangs.Where(n => n.TinhTrangGiaoHang == false && n.DaThanhToan == false&&n.MaShipper!=null).OrderBy(n => n.ThoiGianDat);
                return View(listDSDHCG);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        public ActionResult ChuaGiaoDaThanhToan()
        {
            if (Session["TaiKhoan"] != null)
            {
                var listDSDHCG = db.DonDatHangs.Where(n => n.TinhTrangGiaoHang == false && n.DaThanhToan == true && n.MaShipper != null).OrderBy(n => n.ThoiGianDat);
                return View(listDSDHCG);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        public ActionResult DaThanhToanDaGiao()
        {
            if (Session["TaiKhoan"] != null)
            {
                var listDSDHCG = db.DonDatHangs.Where(n => n.TinhTrangGiaoHang == true && n.DaThanhToan == true && n.MaShipper != null).OrderBy(n => n.ThoiGianDat);
                return View(listDSDHCG);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        
        [HttpGet]
        public ActionResult DuyetDonHang(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                DonDatHang model = db.DonDatHangs.SingleOrDefault(n => n.MaDonDatHang == id);
                if (model == null)
                {
                    return HttpNotFound();
                }
                var listChiTietDH = db.ChiTietDonDatHangs.Where(n => n.MaDonDatHang == id);
                ViewBag.ListChiTietDH = listChiTietDH;
                return View(model);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpPost]
        public ActionResult DuyetDonHang(DonDatHang ddh)
        {
            //Truy Van lay ra du lieu cua don hang do
            DonDatHang ddhUpdate = db.DonDatHangs.Single(n => n.MaDonDatHang == ddh.MaDonDatHang);
            ddhUpdate.DaThanhToan = ddh.DaThanhToan;
            ddhUpdate.TinhTrangGiaoHang = ddh.TinhTrangGiaoHang;
            db.SaveChanges();
            var listChiTietDH = db.ChiTietDonDatHangs.Where(n => n.MaDonDatHang == ddh.MaDonDatHang);
            ViewBag.ListChiTietDH = listChiTietDH;
            ViewBag.ThongBaoDuyet = "Đã lưu thành công";
            return View(ddhUpdate);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyDonHang/ChuaGiaoDaThanhToan.cshtml
@using DoAnChuyenNganh.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Các đơn hàng chưa giao, đã thanh toán";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}

<h2 class="title1">Quản lý đơn hàng (Danh sách đơn hàng chưa giao và đã thanh toán)</h2>
<br />
<ul class="tabs">
    <li role="presentation" class="tablinks"><a href="@Url.Action("DonHangChuaCoShipper", "QuanLyDonHang")">Đơn hàng chưa có shipper</a></li>
    <li role="presentation" class="tablinks"><a href="@Url.Action("ChuaThanhToanChuaGiao", "QuanLyDonHang")">Chưa thanh toán và chưa giao</a></li>
    <li role="presentation" class="tablinks active"><a href="@Url.Action("ChuaGiaoDaThanhToan", "QuanLyDonHang")">Chưa giao và đã thanh toán</a></li>
    <li role="presentation" class="tablinks"><a href="@Url.Action("DaThanhToanDaGiao", "QuanLyDonHang")">Đã giao & Đã thanh toán </a></li>
</ul>
<br />
<br />
@grid.GetHtml(
       tableStyle: "divTable",
       headerStyle: "gridHead",
       footerStyle: "gridFooter",
       rowStyle: "gridRow",
       alternatingRowStyle: "gridAltRow",
        columns: grid.Columns(
               grid.Column("MaDonDatHang", header: "Mã đơn"),
               grid.Column("MaShipper", header: "Tên Shipper", format: p => p.MaShipper != null ? p.Shipper.HoTen : ""),
               grid.Column("MaKho", header: "Thuộc Kho", format: p => p.MaKho != null ? p.Kho.TenKho : ""),
               grid.Column("ThoiGianDat", header: "Ngày đặt"),
               grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
               grid.Column("DaThanhToan", "Đã thanh toán"),
               grid.Column("DinhViKhachHang", "Định vị khách hàng"),
               grid.Column("ThoiGianGiao", header: "Thời gian dự kiến giao (phút)"),
               grid.Column(format: p => Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDonDatHang }, new { @target = "banml" }))
               ))
<style>
    .divTable {
        border: 1px solid #999999;
        width: 100%;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    /*.gridRow{
            color: #fff;
            background-color: blueviolet;
        }
        .gridAltRow{
            color: #fff;
            background-color: darkorange;
        }*/
</style>
<style>
    .FooterAdmin {
        display: none;
    }

    .tabs {
        display: flex;
    }

    .tablinks {
        border: none;
        outline: none;
        cursor: pointer;
        width: 100%;
        padding: 1rem;
        font-size: 13px;
        text-transform: uppercase;
        font-weight: 600;
        transition: 0.2s ease;
    }

        .tablinks:hover {
            background: aqua;
            color: #fff;
        }
        /* Tab active */
        .tablinks.active {
            background: aqua;
            color: #fff;
        }

    /* tab content */
    .tabcontent {
        display: none;
    }
        /* Text*/
        .tabcontent p {
            color: #333;
            font-size: 16px;
        }
        /* tab content active */
        .tabcontent.active {
            display: block;
        }
</style>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyDonHang/ChuaThanhToanChuaGiao.cshtml
@using DoAnChuyenNganh.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Đơn hàng chưa thanh toán, chưa giao";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}


<h2 class="title1">Quản lý đơn hàng (Danh sách đơn hàng chưa giao và chưa thanh toán)</h2>
<br />
<ul class="tabs">
    <li role="presentation" class="tablinks"><a href="@Url.Action("DonHangChuaCoShipper", "QuanLyDonHang")">Đơn hàng chưa có shipper</a></li>
    <li role="presentation" class="tablinks active"><a href="@Url.Action("ChuaThanhToanChuaGiao", "QuanLyDonHang")">Chưa thanh toán và chưa giao</a></li>
    <li role="presentation" class="tablinks "><a href="@Url.Action("ChuaGiaoDaThanhToan", "QuanLyDonHang")">Chưa giao và đã thanh toán</a></li>
    <li role="presentation" class="tablinks"><a href="@Url.Action("DaThanhToanDaGiao", "QuanLyDonHang")">Đã giao & Đã thanh toán </a></li>
</ul>
<br />
<br />
@grid.GetHtml(
       tableStyle: "divTable",
       headerStyle: "gridHead",
       footerStyle: "gridFooter",
       rowStyle: "gridRow",
       alternatingRowStyle: "gridAltRow",
        columns: grid.Columns(
                grid.Column("MaDonDatHang", header: "Mã đơn"),
               grid.Column("MaShipper", header: "Tên Shipper", format: p => p.MaShipper != null ? p.Shipper.HoTen : ""),
               grid.Column("MaKho", header: "Thuộc Kho", format: p => p.MaKho != null ? p.Kho.TenKho : ""),
               grid.Column("ThoiGianDat", header: "Ngày đặt"),
               grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
               grid.Column("DaThanhToan", "Đã thanh toán"),
               grid.Column("DinhViKhachHang", "Định vị khách hàng"),
               grid.Column("ThoiGianGiao", header: "Thời gian dự kiến giao (phút)"),
               grid.Column(format: p => Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDonDatHang }, new { @target = "banml" }))
               ))
<style>
    .divTable {
        border: 1px solid #999999;
        width: 100%;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    /*.gridRow{
            color: #fff;
            background-color: blueviolet;
        }
        .gridAltRow{
            color: #fff;
            background-color: darkorange;
        }*/
</style>
<style>
    .FooterAdmin {
        display: none;
    }

    .tabs {
        display: flex;
    }

    .tablinks {
        border: none;
        outline: none;
        cursor: pointer;
        width: 100%;
        padding: 1rem;
        font-size: 13px;
        text-transform: uppercase;
        font-weight: 600;
        transition: 0.2s ease;
    }

        .tablinks:hover {
            background: aqua;
            color: #fff;
        }
        /* Tab active */
        .tablinks.active {
            background: aqua;
            color: #fff;
        }

    /* tab content */
    .tabcontent {
        display: none;
    }
        /* Text*/
        .tabcontent p {
            color: #333;
            font-size: 16px;
        }
        /* tab content active */
        .tabcontent.active {
            display: block;
        }
</style>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyDonHang/DaThanhToanDaGiao.cshtml
@using DoAnChuyenNganh.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Đơn hàng đã thanh toán, đã giao";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}

<h2 class="title1">Quản lý đơn hàng (Danh sách đơn hàng đã giao và đã thanh toán)</h2>
<br />
<ul class="tabs">
    <li role="presentation" class="tablinks"><a href="@Url.Action("DonHangChuaCoShipper", "QuanLyDonHang")">Đơn hàng chưa có shipper</a></li>
    <li role="presentation" class="tablinks"><a href="@Url.Action("ChuaThanhToanChuaGiao", "QuanLyDonHang")">Chưa thanh toán và chưa giao</a></li>
    <li role="presentation" class="tablinks "><a href="@Url.Action("ChuaGiaoDaThanhToan", "QuanLyDonHang")">Chưa giao và đã thanh toán</a></li>
    <li role="presentation" class="tablinks active"><a href="@Url.Action("DaThanhToanDaGiao", "QuanLyDonHang")">Đã giao & Đã thanh toán </a></li>
</ul>
<br />
<br />
@grid.GetHtml(
       tableStyle: "divTable",
       headerStyle: "gridHead",
       footerStyle: "gridFooter",
       rowStyle: "gridRow",
       alternatingRowStyle: "gridAltRow",
        columns: grid.Columns(
               grid.Column("MaDonDatHang", header: "Mã đơn"),
               grid.Column("MaShipper", header: "Tên Shipper", format: p => p.MaShipper != null ? p.Shipper.HoTen : ""),
               grid.Column("MaKho", header: "Thuộc Kho", format: p => p.MaKho != null ? p.Kho.TenKho : ""),
               grid.Column("ThoiGianDat", header: "Ngày đặt"),
               grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
               grid.Column("DaThanhToan", "Đã thanh toán"),
               grid.Column("DinhViKhachHang", "Định vị khách hàng"),
               grid.Column("ThoiGianGiao", header: "Thời gian dự kiến giao (phút)"),
               grid.Column(format: p => Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDonDatHang }, new { @target = "banml" }))
               ))
<style>
    .divTable {
        border: 1px solid #999999;
        width: 100%;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    /*.gridRow{
            color: #fff;
            background-color: blueviolet;
        }
        .gridAltRow{
            color: #fff;
            background-color: darkorange;
        }*/
</style>
<style>
    .FooterAdmin {
        display: none;
    }

    .tabs {
        display: flex;
    }

    .tablinks {
        border: none;
        outline: none;
        cursor: pointer;
        width: 100%;
        padding: 1rem;
        font-size: 13px;
        text-transform: uppercase;
        font-weight: 600;
        transition: 0.2s ease;
    }

        .tablinks:hover {
            background: aqua;
            color: #fff;
        }
        /* Tab active */
        .tablinks.active {
            background: aqua;
            color: #fff;
        }

    /* tab content */
    .tabcontent {
        display: none;
    }
        /* Text*/
        .tabcontent p {
            color: #333;
            font-size: 16px;
        }
        /* tab content active */
        .tabcontent.active {
            display: block;
        }
</style>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyDonHang/DonHangChuaCoShipper.cshtml
@using DoAnChuyenNganh.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Đơn hàng chưa có Shipper";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}

<h2 class="title1">Quản lý đơn hàng (Danh sách đơn hàng đã giao và đã thanh toán)</h2>
<br />
<ul class="tabs">
    <li role="presentation" class="tablinks active"><a href="@Url.Action("DonHangChuaCoShipper", "QuanLyDonHang")">Đơn hàng chưa có shipper</a></li>
    <li role="presentation" class="tablinks"><a href="@Url.Action("ChuaThanhToanChuaGiao", "QuanLyDonHang")">Chưa thanh toán và chưa giao</a></li>
    <li role="presentation" class="tablinks "><a href="@Url.Action("ChuaGiaoDaThanhToan", "QuanLyDonHang")">Chưa giao và đã thanh toán</a></li>
    <li role="presentation" class="tablinks "><a href="@Url.Action("DaThanhToanDaGiao", "QuanLyDonHang")">Đã giao & Đã thanh toán </a></li>
</ul>
<br />
<br />
@grid.GetHtml(
       tableStyle: "divTable",
       headerStyle: "gridHead",
       footerStyle: "gridFooter",
       rowStyle: "gridRow",
       alternatingRowStyle: "gridAltRow",
        columns: grid.Columns(
               grid.Column("MaDonDatHang", header: "Mã đơn"),
               grid.Column("MaShipper", header: "Tên Shipper", format: p => p.MaShipper != null ? p.Shipper.HoTen : ""),
               grid.Column("MaKho", header: "Thuộc Kho", format: p => p.MaKho != null ? p.Kho.TenKho : ""),
               grid.Column("ThoiGianDat", header: "Ngày đặt"),
               grid.Column("DinhViKhachHang", "Định vị khách hàng"),
               grid.Column("ThoiGianGiao", header: "Thời gian dự kiến giao (phút)")            
               ))
<style>
    .divTable {
        border: 1px solid #999999;
        width: 100%;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    /*.gridRow{
            color: #fff;
            background-color: blueviolet;
        }
        .gridAltRow{
            color: #fff;
            background-color: darkorange;
        }*/
</style>
<style>
    .FooterAdmin {
        display: none;
    }

    .tabs {
        display: flex;
    }

    .tablinks {
        border: none;
        outline: none;
        cursor: pointer;
        width: 100%;
        padding: 1rem;
        font-size: 13px;
        text-transform: uppercase;
        font-weight: 600;
        transition: 0.2s ease;
    }

        .tablinks:hover {
            background: aqua;
            color: #fff;
        }
        /* Tab active */
        .tablinks.active {
            background: aqua;
            color: #fff;
        }

    /* tab content */
    .tabcontent {
        display: none;
    }
        /* Text*/
        .tabcontent p {
            color: #333;
            font-size: 16px;
        }
        /* tab content active */
        .tabcontent.active {
            display: block;
        }
</style>

DoAnChuyenNganh/DoAnChuyenNganh/Views/QuanLyDonHang/DuyetDonHang.cshtml
@using DoAnChuyenNganh.Models
@model DonDatHang
@{
    ViewBag.Title = "Duyệt đơn hàng";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}
<div>
    @Html.ActionLink("Quay lại danh sách", "DonHangChuaCoShipper")
</div>
<h2>Thông tin đơn hàng của shipper <font color="#f65e84">@Model.Shipper.HoTen</font></h2>
<h3 class="control-label" style="color: #3c763d">@ViewBag.ThongBaoDuyet</h3>
@using (Html.BeginForm())
{
    <div class="ChiTietDonHang table">
        @{ IEnumerable<ChiTietDonDatHang> listChiTietDH = (IEnumerable<ChiTietDonDatHang>)ViewBag.ListChiTietDH;}
        <table class="table" id="table">
            <tr>
                <td colspan="4">
                    <table style="width:100%;">
                        <tr>
                            <td>Mã đơn hàng: <b style="color:red;">@Model.MaDonDatHang @Html.Hidden("MaDonDatHang", @Model.MaDonDatHang)</b></td>
                            <td>Mã shipper: <b style="color:red;">@Model.Shipper.MaShipper </b></td>
                            <td>Tên Shipper: <b style="color:red;">@Model.Shipper.HoTen </b></td>
                            <td>Ngày đặt: @Model.ThoiGianDat.Value.ToString("dd-MM-yyyy HH:mm:ss")</td>
                            <td>Đã thanh toán: @Html.EditorFor(model => model.DaThanhToan)</td>
                            <td>Đã giao: @Html.EditorFor(model => model.TinhTrangGiaoHang)</td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td><b>Sản phẩm</b></td>
                <td><b>hình ảnh</b></td>
                <td><b>Số lượng đặt</b></td>
                <td><b>Đơn giá đặt</b></td>
            </tr>
            @foreach (var item in listChiTietDH)
            {
                <tr>
                    <td>@item.MatHang.TenMatHang</td>
                    <td><img width="150" height="150" src="@Url.Content("~/Content/Images/"+item.MatHang.HinhAnh)" /></td>
                    <td>@item.SoLuong</td>
                    <td>@item.DonGia</td>
                </tr>
            }
            <tr>
                <td align="right" colspan="4">Tổng số lượng: @Model.ChiTietDonDatHangs.Sum(n => n.SoLuong) sản phẩm</td>
            </tr>
            <tr>
                <td align="right" colspan="4">Tổng tiền: @Model.ChiTietDonDatHangs.Sum(n => n.MatHang.DonGia * n.SoLuong).Value.ToString("#,##") đồng</td>
            </tr>
        </table>
        <br /><br />
        <input type="button" value="In đơn hàng" id="btnInDonHang" />
        <input type="submit" value="Lưu đơn hàng" />
    </div>
}
<script>
    $("#btnInDonHang").click(function () {
        var content = "<table>" + $("#table").html();
        InDonHang(content);
    });
    function InDonHang(content) {
        var printWindow = window.open('', '', 'height=400,width=800');
        printWindow.document.write('<html><head><title>DIV Contents</title>');
        printWindow.document.write('<head><body>');
        printWindow.document.write(content);
        printWindow.document.write('</body><html>');
        printWindow.document.close();
        printWindow.print();
    }
</script>